# tasks for project creation
---
- name: verify that roles are installed
  command: ansible-galaxy role list
  register: output
  set_fact:
    installed: "{{ output.stdout }}"
- name: install uninstalled roles
  command: ansible-galaxy role install {{ item }}
  loop:
    - "itayharell.index_create"
    - "itayharell.token_create"
  when: installed is not search({{ item }})
- name: validate that priject_name is defined
  fail:
    msg: project_name is not defined
  when: project_name is not defined
- name: create app in deployer and cluster master
  become: true
  file:
    path: /splunk/splunk/etc/{{ item }}/{{ project_name }}/local
    state: directory
    owner: splunk
    group: splunk
  with_items:
    - "shcluster/apps"
    - "master-apps"
- name: create index
  include_role:
    name: itayharell.index_create
  vars:
    index_name: "{{ project_name }}_logs"
- name: create hec token
  include_role:
    name: itayharell.token_create
  vars:
    token_name: "{{ project_name }}_token"
- name: distrebute to search heads
  run_once: truecd 
  become: true
  become_user: splunk
  shell: /splunk/splunk/bin/splunk apply shcluster-bundle --answer-yes -target https://{{groups['searchheads'][0] }}:8089 -auth admin:Babay0ff!
- name: distrebute to indexers
  run_once: true
  become: true
  become_user: splunk
  shell: /splunk/splunk/bin/splunk apply cluster-bundle --answer-yes -target https://{{groups['indexers'][0] }}:8089 -auth admin:Babay0ff!
